module.exports = {
  extends: ['plugin:vitest/all'],
  plugins: ['vitest'],
  rules: {
    'vitest/consistent-test-filename': 0,
    'vitest/consistent-test-it': [2, { fn: 'it', withinDescribe: 'it' }],
    'vitest/expect-expect': 2,
    'vitest/max-expects': 0,
    'vitest/max-nested-describe': 0,
    'vitest/no-alias-methods': 2,
    'vitest/no-commented-out-tests': 2,
    'vitest/no-conditional-expect': 2,
    'vitest/no-conditional-in-test': 2,
    'vitest/no-conditional-tests': 2,
    'vitest/no-disabled-tests': 2,
    'vitest/no-done-callback': 2,
    'vitest/no-duplicate-hooks': 2,
    'vitest/no-focused-tests': 2,
    'vitest/no-hooks': 0,
    'vitest/no-identical-title': 2,
    'vitest/no-import-node-test': 2,
    'vitest/no-interpolation-in-snapshots': 2,
    'vitest/no-large-snapshots': [
      2,
      {
        maxSize: 50,
        inlineMaxSize: 0,
        allowedSnapshots: [],
      },
    ],
    'vitest/no-mocks-import': 2,
    'vitest/no-restricted-matchers': 2,
    'vitest/no-restricted-vi-methods': 2,
    'vitest/no-standalone-expect': 2,
    'vitest/no-test-prefixes': 2,
    'vitest/no-test-return-statement': 2,
    'vitest/prefer-called-with': 2,
    'vitest/prefer-comparison-matcher': 2,
    'vitest/prefer-each': 2,
    'vitest/prefer-equality-matcher': 2,
    'vitest/prefer-expect-assertions': 0,
    'vitest/prefer-expect-resolves': 2,
    'vitest/prefer-hooks-in-order': 2,
    'vitest/prefer-hooks-on-top': 0,
    'vitest/prefer-lowercase-title': 2,
    'vitest/prefer-mock-promise-shorthand': 2,
    'vitest/prefer-snapshot-hint': 0,
    'vitest/prefer-spy-on': 2,
    'vitest/prefer-strict-equal': 2,
    'vitest/prefer-to-be': 2,
    'vitest/prefer-to-be-falsy': 2,
    'vitest/prefer-to-be-object': 2,
    'vitest/prefer-to-be-truthy': 2,
    'vitest/prefer-to-contain': 2,
    'vitest/prefer-to-have-length': 2,
    'vitest/prefer-todo': 2,
    'vitest/require-hook': 0,
    'vitest/require-local-test-context-for-concurrent-snapshots': 0,
    'vitest/require-to-throw-message': 2,
    'vitest/require-top-level-describe': 2,
    'vitest/valid-describe-callback': 2,
    'vitest/valid-expect': 2,
    'vitest/valid-title': 2,
  },
}
